<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Description>IdentityManager is an user management tool for ASP.NET Core. Maintained by Rock Solid Knowledge.</Description>
    <VersionPrefix>1.0.2</VersionPrefix>
    <Authors>Scott Brady</Authors>
    <AssemblyName>IdentityManager2</AssemblyName>
    <PackageId>IdentityManager2</PackageId>
    <PackageTags>IdentityManager;IdentityManager2;Identity</PackageTags>
    <PackageIconUrl>https://identityserver.github.io/Documentation/assets/images/icons/IDmanager_icon144.jpg</PackageIconUrl>
    <PackageProjectUrl>https://github.com/IdentityManager/IdentityManager2</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/IdentityManager/IdentityManager2/blob/master/LICENSE</PackageLicenseUrl>
    <!--<GenerateDocumentationFile>true</GenerateDocumentationFile>-->
    <!--<PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>-->
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*.ico" />
    <EmbeddedResource Include="Assets\**\*.jpg" />
    <EmbeddedResource Include="Assets\**\*.png" />
    <EmbeddedResource Include="Assets\**\*.js" />
    <EmbeddedResource Include="Assets\Templates\**" />
    <EmbeddedResource Include="Assets\Content\fonts\**" />
    <EmbeddedResource Include="Assets\Content\*.css" />
    <None Include="package.json" />
    <None Include="package-lock.json" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityManager2.Apis\IdentityManager2.Apis.csproj" />
  </ItemGroup>

</Project>
